import { useEffect, useRef } from 'react';
import { ckeditorConfig } from '../config/ckeditorConfig';
import { openMathDialog } from './MathLiveDialog';
import { mathConfig } from '../config/mathConfig';
import { renderAllMathInEditor } from '../lib/mathRenderer';

interface CKEditor4Props {
    initialData?: string;
    onChange?: (data: string) => void;
    onReady?: (editor: any) => void;
}

const CKEditor4 = ({ initialData, onChange, onReady }: CKEditor4Props) => {
    const editorRef = useRef<HTMLDivElement>(null);
    const editorInstanceRef = useRef<any>(null);

    useEffect(() => {
        const loadScripts = async () => {
            // Check if scripts are already loaded
            if (!window.CKEDITOR) {
                const ckeditorScript = document.createElement('script');
                ckeditorScript.src = 'https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js';
                ckeditorScript.async = true;
                document.body.appendChild(ckeditorScript);
                await new Promise((resolve) => {
                    ckeditorScript.onload = resolve;
                });
            }

            const mathLiveStylesId = 'mathlive-styles';
            if (!document.getElementById(mathLiveStylesId)) {
                const mathLiveStyles = document.createElement('link');
                mathLiveStyles.id = mathLiveStylesId;
                mathLiveStyles.rel = 'stylesheet';
                mathLiveStyles.href = 'https://unpkg.com/mathlive@0.95.5/dist/mathlive-static.css';
                document.head.appendChild(mathLiveStyles);
            }

            // Load MathLive
            if (!window.MathLive) {
                await import('https://esm.run/mathlive').then((mathlive) => {
                    window.MathLive = mathlive;
                    if (mathConfig.outputFormat === 'mathlive') {
                        mathlive.renderMathInDocument();
                    }
                });
            }



            if (editorRef.current && window.CKEDITOR) {
                // If an instance already exists, destroy it first
                if (window.CKEDITOR.instances[editorRef.current.id]) {
                    window.CKEDITOR.instances[editorRef.current.id].destroy();
                }

                const editor = window.CKEDITOR.replace(editorRef.current, ckeditorConfig);
                if (!editor) {
                    console.error('Failed to create CKEditor instance');
                    return;
                }

                editor.on('instanceReady', () => {


                    if (initialData) {
                        editor.setData(initialData);
                        setTimeout(() => {
                            renderAllMathInEditor(editor);
                        }, 2500);
                    }
                    if (onReady) {
                        onReady(editor);
                    }
                });

                editor.on('change', () => {
                    if (onChange) {
                        onChange(editor.getData());
                    }
                    // Optional: re-render on change if needed, 
                    // though usually the dialog handles it.
                });

                editor.on('dataReady', () => {
                    renderAllMathInEditor(editor);
                });

                // MathLive Integration
                editor.addCommand('insertMath', {
                    exec: (editor: any) => {
                        openMathDialog(editor);
                    },
                });

                editor.ui.addButton('InsertMath', {
                    label: 'Insert Math',
                    command: 'insertMath',
                    toolbar: 'custom',
                    icon: 'https://cdn-icons-png.flaticon.com/512/3771/3771471.png',
                });

                editor.on('contentDom', () => {
                    editor.editable().on('click', (evt: any) => {
                        const target = evt.data.getTarget();

                        // 1. Try to find if we clicked a math container directly or its ancestor
                        let mathElement = target.getAscendant((el: any) => {
                            return el.hasClass && (
                                el.hasClass('math-span') ||
                                el.hasClass('math-div') ||
                                el.hasClass('math-texzilla-svg') ||
                                el.hasClass('math-texzilla-png') ||
                                el.hasClass('tex')
                            );
                        }, true);

                        // 2. If not found, we might have clicked a MathML element (<math>)
                        // generated by TeXZilla. The hidden source span is the previous sibling.
                        if (!mathElement) {
                            const mathmlRoot = target.getAscendant('math', true);
                            if (mathmlRoot) {
                                const prev = mathmlRoot.getPrevious();
                                if (prev && prev.hasClass && (prev.hasClass('math-span') || prev.hasClass('tex'))) {
                                    mathElement = prev;
                                }
                            }
                        }

                        if (mathElement) {
                            const latex = mathElement.getAttribute('data-latex') || mathElement.getText();
                            openMathDialog(editor, latex, mathElement);
                        }
                    });
                });

                editorInstanceRef.current = editor;
            }
        };

        loadScripts();

        return () => {
            if (editorInstanceRef.current) {
                editorInstanceRef.current.destroy();
                editorInstanceRef.current = null;
            }
        };
    }, []);

    return <div ref={editorRef} />;
};

export default CKEditor4;
